# Trigger workflow manually for testing purposes

name: Trigger Manual Test

on:
  workflow_dispatch:

jobs:
  git-tag-increment:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Automatic Tagging of Releases
        id: increment-git-tag
        run: |
          bash ./scripts/git_update.sh -v patch

      - name: Report
        run: echo ${{ steps.increment-git-tag.outputs.git-tag }}

