# Trigger workflow manually for testing purposes

name: Trigger Manual Test

on:
  workflow_dispatch:
env:
  IMAGE_NAME: ${{ var.DOCKER_IMAGE_NAME }}
  REPOSITORY_NAME: ${{ var.CLOUD_REPOSITORY_NAME }} # Google Cloud Artifact Registry Repository Name
  PROJECT_ID: ${{ var.CLOUD_PROJECT_ID }} # Google Cloud Project ID
  SERVICE: ${{ var.CLOUD_SERVICE_NAME }} # Google Cloud Run Service Name
  GCR_REGION: ${{ var.CLOUD_REGION }} # Google Cloud Run Service Region Name
  GAR_REGION: ${{ var.CLOUD_REGION }} # Google Artifact Registry Region Name

jobs:
  test-job:

    runs-on: ubuntu-latest

    steps:
      - name: Display Variables
        run: |
          echo "Image Name : $IMAGE_NAME"
          echo "Repository Name : $REPOSITORY_NAME"
          echo "Project ID : $PROJECT_ID"
          echo "Service Name  $SERVICE
          echo "Cloud Run Service Region : $GCR_REGION"
          echo "Artifact Registry Region : $GAR_REGION"

